name: zenobase-frontend
services:
  zenobase:
    container_name: zenobase-nginx
    image: zenobase-nginx:latest
    ports:
        - "8080:80"
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:9000
    deploy:
        resources:
            limits:
                memory: 1g
